INSERT INTO PERSON (ID,NAME) values(101,'Jesse');
INSERT INTO PERSON (ID,NAME) values(102,'Jeffrey');
INSERT INTO PERSON (ID,NAME) values(2,'Randall');
INSERT INTO PET(ID,AGE,GENDER,NAME,TYPE) VALUES(1,1,'Male','Spot','Dog');
INSERT INTO PET(ID,AGE,GENDER,NAME,TYPE) VALUES(0,1,'Male','Sully','Cat');