name: CI/CD with Maven

on:
  push:
    branches: ["main"]
  pull_requests:
    branches: ["main"]

  jobs:
    build:
      runs-on: ubuntu-latest

      steps:
        - uses: actions/checkout@v3
        - name: Setup JDK 17
          uses: actions/setup-java@v3
          with:
            java-version: '17'
            distributions: 'temurin'
            cache: maven
        - name: Package
          run: mvn -B package --file pom.xml
        - name: Build
          run: mvn clean install
        - name: Test
          run: mvn test