name: UI CI/CD Pipeline

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

permissions:
  contents: read

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: ['18.x', '20.x']
        ui-directory: './purrgent-care-ui'

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - run: npm --prefix ${{ matrix.ui-directory }} install ${{ matrix.ui-directory }}
      - run: npm run build --prefix ${{ matrix.ui-directory }} --if-present
      - run: npm run test --prefix ${{ matrix.ui-directory }}
